<LoginScreen>:
    GridLayout:
        GridLayout:
            Label:
                text:"User Login"
            TextInput:
                on_hint_text:"Username"
            TextInput
                on_hint_text:"Password"
            Button:
                text:"Login"
        GridLayout:
            cols:2
            Button:
                text:"Forgot Password?"
            Button:
                text:"Sign Up"

<RootWidget>:
    LoginScreen:
        name:"login_screen"
